# Build settings
permalink: /:categories/:title # pretty # date # /blog/:category/:title #/blog/:year/:title/
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-multiple-languages-plugin

JEKYLL_ENV: production

emptyArray: []

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Dixon Martinez
description: ""
keywords: ""
url: "https://dixonmartinez.github.io"
baseurl: ""

repo: http://github.com/nandomoreirame/end2end
disqus_shortname: "damartinez"
disqus_site_shortname: "damartinez"

# Google
# Analytics
google-analytics: "UA-87552605-4"
# Adsense
google-adsense: ca-pub-6139449870308039


# Author settings
author:
  name: Dixon Martinez
  job: Backend Engineer
  bio: "Entusiasta desempeño, diseño receptivo y usabilidad, siempre buscando el mejor proyecto y un buen café."
  thumb: /images/author.jpg #https://avatars2.githubusercontent.com/u/2453563?s=160&v=4
  email: dixonalvarezm@gmail.com
  url: https://dixonmartinez.github.io
  github_username: dixonmartinez
  twitter_username: AMartinezDixon
  facebook_username: dixonjose.martinez
  linkedin_username: dixon-martinez

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# navbar pages
navbar_en:
  home:
    slug: '/'
    slug_compare: '/'
    title: 'Home'
    slug_trl: 'inicio'
  about:
    slug: 'about'
    slug_compare: '/about/'
    title: 'About'
    slug_trl: 'sobre'
  blog:
    slug: 'blog'
    slug_compare: '/blog/'
    title: 'Blog'
    slug_trl: 'blog'
  

navbar_es:
  home:
    slug: '/'
    slug_compare: '/'
    title: 'Inicio'
    slug_trl: '/'
  about:
    slug: 'sobre'
    slug_compare: '/sobre/'
    title: 'Sobre Mí'
    slug_trl: 'about'
  blog:
    slug: 'blog'
    slug_compare: '/blog/'
    title: 'Blog'
    slug_trl: 'blog'

exclude: ["vendor","config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]

languages: ["es", "en"]
defaultLang: es
languageNames:
  es: Spanish
  en: English