# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Seo 
title: Dixon Martinez
email: dixonalvarezm@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My site by create tips of programing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dixonmartinez.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: Dixon Martinez
twitter:
  username: AMartinezDixon
  card: summary
  creator: AMartinezDixon
facebook:
  username: dixonjose.martinez
social:
  name: Dixon Martinez
  links:
    - https://twitter.com/AMartinezDixon
    - https://www.facebook.com/dixonjose.martinez
    - https://www.linkedin.com/in/dixon-martinez
    - https://github.com/dixonmartinez
    - https://www.instagram.com/adartinez
    - https://twitter.com/AMartinezDixon
lang: en_US

#defaults:
#  - scope:
#    path: ""
#    values:
#      image: /assets/images/default-card.png


twitter_username: AMartinezDixon
github_username: dixonmartinez
facebook_username: dixonjose.martinez
instagram_username: adartinez
linkedin_username: dixon-martinez
youtube_username: channel/UCpF1nzCQKun7ONAif-8tx4g 
#channel/UCBWSP14JeZ7RWIZGX9ZXEAw

# googleplus_username: 102986034740417849624
disqus:
   shortname: damartinez

# Google
# Analytics
google_analytics: "UA-87552605-4"
# Adsense
google_adsense: ca-pub-6139449870308039


# Build settings
highlighter: rouge
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
#  - jekyll-multiple-languages

# Posts Configuration
show_excerpts: true
permalink: pretty # /:categories/:title # pretty # date # /blog/:category/:title #/blog/:year/:title/
comments: true
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  
header_pages:
  - index.md
  - blog/index.html
  - contact.md
  - about.md
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
#exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#   - utils/

# Pagination
paginate: 3
paginate_path: "/blog/page:num/"

# If not config, the first item of languages will be used as the default.
